apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y1pp1hgc1-go 
  janus-idp.io/tekton: y1pp1hgc1-go
  backstage.io/kubernetes-id: y1pp1hgc1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y1pp1hgc1-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  